### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [CalvinAllen/OpenInNotepadPlusPlus#3]

**Comment by jvsca** [comment]
Change in file source.extension.vsixmanifest:
From:
`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0]" />`
To:
`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0,)" />`

**Comment by CalvinAllen** [comment]
Thanks for the fix @jvsca!

**Comment by jvsca** [comment]
You are welcome @CalvinAllen.
