### ISSUE TITLE
Does not handle files in an SSIS project

### ISSUE THREAD

**Issue by grambo25** [CalvinAllen/OpenInNotepadPlusPlus#4]
If I have an SSIS project with a dtsx packages in it, I get the following error when trying to Open In Notepad++ on any of the dtsx packages.

6/9/2016 3:12:54 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenInNotepadPlusPlus.Helpers.ProjectHelpers.GetSelectedPath(DTE2 dte) in C:\projects\openinnotepadplusplus\src\Helpers\ProjectHelpers.cs:line 17
   at OpenInNotepadPlusPlus.Commands.OpenNotepadPlusPlusCommand.OpenPath(Object sender, EventArgs e) in C:\projects\openinnotepadplusplus\src\Commands\OpenNotepadPlusPlusCommand.cs:line 39

**Comment by CalvinAllen** [comment]
I haven't tested with that type of project before, I'll see if I can reproduce it.

**Comment by CalvinAllen** [comment]
Can you give this build a try?

http://vsixgallery.com/extension/E476F42B-1D6C-4C78-B56B-42CF7366D5E0/

If everything works out fine, I'll push the extension to the main gallery.

**Comment by grambo25** [comment]
Sorry I am just now getting back to this.  I am unable to download the new build.  The link for the download button is broken.

**Comment by CalvinAllen** [comment]
Interesting.  I don't maintain that site, so I'm not sure what happened there.  Try the attached zip file (the VSIX is inside)

[OpenInNotepadPlusPlus.zip](https://github.com/CalvinAllen/OpenInNotepadPlusPlus/files/320579/OpenInNotepadPlusPlus.zip)

**Comment by grambo25** [comment]
I tried it out and it looks good.  Thanks!
