### ISSUE TITLE
Couldn't resolve the folder

### ISSUE THREAD

**Issue by deepuHub** [CalvinAllen/OpenInNotepadPlusPlus#5]
I have VS Enterprise 2015 Update 2 and Open in Notepad++ 1.0.8; 

I am not able to open any project or solution or a file using the plugin. I get the pop-up error "Couldn't resolve the folder"

**Comment by CalvinAllen** [comment]
Very interesting - you're running the same configuration I am.

Where is Notepad++ installed?  Was the plugin able to find the executable?  (Check Settings | Open in Notepad++)

**Comment by deepuHub** [comment]
Where is Notepad++ installed? 
D:\Program Files (x86)\Notepad++

Issue:
Oh I see it.. The Install path field was empty in the Options dialog. you might have to check may be..

Resolved!
1. I set the "Install path" in VS->Tools->Options->Open in Notepad++ to "D:\Program Files (x86)\Notepad++\notepad++.exe"
2. Restart VS
3. Works cool!

Thanks so much Calvin! I am going to use this extension extensively now!!

**Comment by CalvinAllen** [comment]
Great, thanks @deepuHub !

Just out of curiosity, is "D" the system drive, or is that a separate drive where its installed?

**Comment by deepuHub** [comment]
"C" is the system drive running fast out of space :-) So, I had installed it on "D".
